"""Add address_proof and device_id

Revision ID: 4a7da3c07e64
Revises: 23d31f512e23
Create Date: 2026-07-14 08:57:57.672571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a7da3c07e64'
down_revision: Union[str, None] = '23d31f512e23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_bookings_created_at', table_name='bookings')
    op.drop_index('idx_bookings_guest_id', table_name='bookings')
    op.drop_index('idx_bookings_space_date_status', table_name='bookings')
    op.drop_index('idx_bookings_status', table_name='bookings')
    # Fix for enum casting:
    op.execute("ALTER TABLE categories ALTER COLUMN listing_type TYPE listingtype USING listing_type::listingtype")
    op.drop_index('idx_conversations_guest_id', table_name='conversations')
    op.drop_index('idx_conversations_host_id', table_name='conversations')
    op.drop_index('idx_conversations_last_message_at', table_name='conversations')
    op.drop_index('idx_favorites_user_space', table_name='favorites')
    op.drop_index('idx_messages_conversation_id', table_name='messages')
    op.drop_index('idx_messages_created_at', table_name='messages')
    op.drop_index('idx_messages_sender_id', table_name='messages')
    op.drop_index('idx_notifications_created_at', table_name='notifications')
    op.drop_index('idx_notifications_user_id_read', table_name='notifications')
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_password_reset_token', table_name='password_reset_tokens')
    op.drop_index('idx_password_reset_user_expires', table_name='password_reset_tokens')
    op.drop_index('ix_password_reset_tokens_user_id', table_name='password_reset_tokens')
    op.drop_index('idx_reviews_booking_id', table_name='reviews')
    op.drop_index('idx_reviews_reviewee_id', table_name='reviews')
    op.drop_index('idx_reviews_reviewer_id', table_name='reviews')
    op.alter_column('spaces', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('idx_spaces_category_id', table_name='spaces')
    op.drop_index('idx_spaces_city_state', table_name='spaces')
    op.drop_index('idx_spaces_host_id', table_name='spaces')
    op.drop_index('idx_spaces_is_active_approved', table_name='spaces')
    op.add_column('users', sa.Column('address_proof_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_device_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('firebase_token', sa.String(), nullable=True))
    op.drop_index('idx_users_cpf', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_is_host', table_name='users')
    op.drop_index('idx_users_phone', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_phone', 'users', ['phone'], unique=True)
    op.create_index('idx_users_is_host', 'users', ['is_host'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=True)
    op.create_index('idx_users_cpf', 'users', ['cpf'], unique=True)
    op.drop_column('users', 'firebase_token')
    op.drop_column('users', 'last_device_id')
    op.drop_column('users', 'address_proof_url')
    op.create_index('idx_spaces_is_active_approved', 'spaces', ['is_active', 'is_approved'], unique=False)
    op.create_index('idx_spaces_host_id', 'spaces', ['host_id'], unique=False)
    op.create_index('idx_spaces_city_state', 'spaces', ['city', 'state'], unique=False)
    op.create_index('idx_spaces_category_id', 'spaces', ['category_id'], unique=False)
    op.alter_column('spaces', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('idx_reviews_reviewer_id', 'reviews', ['reviewer_id'], unique=False)
    op.create_index('idx_reviews_reviewee_id', 'reviews', ['reviewee_id'], unique=False)
    op.create_index('idx_reviews_booking_id', 'reviews', ['booking_id'], unique=False)
    op.create_index('ix_password_reset_tokens_user_id', 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index('idx_password_reset_user_expires', 'password_reset_tokens', ['user_id', 'expires_at'], unique=False)
    op.create_index('idx_password_reset_token', 'password_reset_tokens', ['token'], unique=True)
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_notifications_user_id_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index('idx_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_messages_sender_id', 'messages', ['sender_id'], unique=False)
    op.create_index('idx_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('idx_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.create_index('idx_favorites_user_space', 'favorites', ['user_id', 'space_id'], unique=True)
    op.create_index('idx_conversations_last_message_at', 'conversations', ['last_message_at'], unique=False)
    op.create_index('idx_conversations_host_id', 'conversations', ['host_id'], unique=False)
    op.create_index('idx_conversations_guest_id', 'conversations', ['guest_id'], unique=False)
    op.alter_column('categories', 'listing_type',
               existing_type=sa.Enum('SPACE', 'EQUIPMENT', name='listingtype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_index('idx_bookings_status', 'bookings', ['status'], unique=False)
    op.create_index('idx_bookings_space_date_status', 'bookings', ['space_id', 'date', 'status'], unique=False)
    op.create_index('idx_bookings_guest_id', 'bookings', ['guest_id'], unique=False)
    op.create_index('idx_bookings_created_at', 'bookings', ['created_at'], unique=False)
    # ### end Alembic commands ###
