"""expand_listing_types

Revision ID: 8cae6a2a2681
Revises: 0237b74b830c
Create Date: 2026-07-15 10:29:30.784965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cae6a2a2681'
down_revision: Union[str, None] = '0237b74b830c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE listingtype ADD VALUE IF NOT EXISTS 'SERVICE'")
    op.execute("ALTER TYPE listingtype ADD VALUE IF NOT EXISTS 'VEHICLE'")
    
    op.create_table('category_amenities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('categories', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('categories', sa.Column('parent_group', sa.String(), nullable=True))
    op.add_column('spaces', sa.Column('service_area_description', sa.Text(), nullable=True))
    op.add_column('spaces', sa.Column('years_experience', sa.Integer(), nullable=True))
    op.add_column('spaces', sa.Column('portfolio_url', sa.String(), nullable=True))
    op.add_column('spaces', sa.Column('vehicle_make', sa.String(), nullable=True))
    op.add_column('spaces', sa.Column('vehicle_model', sa.String(), nullable=True))
    op.add_column('spaces', sa.Column('vehicle_year', sa.Integer(), nullable=True))
    op.add_column('spaces', sa.Column('vehicle_length_ft', sa.Float(), nullable=True))
    op.add_column('spaces', sa.Column('engine_hp', sa.Integer(), nullable=True))
    op.add_column('spaces', sa.Column('has_captain', sa.Boolean(), nullable=True))
    op.add_column('spaces', sa.Column('requires_license', sa.Boolean(), nullable=True))
    op.add_column('spaces', sa.Column('embark_location', sa.String(), nullable=True))
    op.alter_column('spaces', 'address_line',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('spaces', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('spaces', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('spaces', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('spaces', 'neighborhood',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('spaces', 'max_guests',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spaces', 'max_guests',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('spaces', 'neighborhood',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('spaces', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('spaces', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('spaces', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('spaces', 'address_line',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('spaces', 'embark_location')
    op.drop_column('spaces', 'requires_license')
    op.drop_column('spaces', 'has_captain')
    op.drop_column('spaces', 'engine_hp')
    op.drop_column('spaces', 'vehicle_length_ft')
    op.drop_column('spaces', 'vehicle_year')
    op.drop_column('spaces', 'vehicle_model')
    op.drop_column('spaces', 'vehicle_make')
    op.drop_column('spaces', 'portfolio_url')
    op.drop_column('spaces', 'years_experience')
    op.drop_column('spaces', 'service_area_description')
    op.drop_column('categories', 'parent_group')
    op.drop_column('categories', 'description')
    op.drop_table('category_amenities')
    # ### end Alembic commands ###
