"""Initial migration

Revision ID: 99e2d648c27b
Revises: 
Create Date: 2026-07-11 15:13:24.157414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99e2d648c27b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_host', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('selfie_url', sa.String(), nullable=True),
    sa.Column('kyc_status', sa.String(), nullable=True),
    sa.Column('kyc_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_verified_host', sa.Boolean(), nullable=True),
    sa.Column('is_pro_host', sa.Boolean(), nullable=True),
    sa.Column('hosting_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avg_response_time_minutes', sa.Integer(), nullable=True),
    sa.Column('stripe_account_id', sa.String(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('BOOKING_REQUEST', 'BOOKING_CONFIRMED', 'BOOKING_CANCELLED', 'REVIEW_RECEIVED', 'PAYMENT_RECEIVED', 'MESSAGE_RECEIVED', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('listing_type', sa.Enum('SPACE', 'EQUIPMENT', name='listingtype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('PISCINA', 'CHURRASQUEIRA', 'SALAO_FESTAS', 'QUADRA', 'ESTUDIO', 'SITIO', 'BRINQUEDOS', 'MOBILIARIO', 'DECORACAO', 'SERVICOS', 'OUTRO', name='spacecategory'), nullable=False),
    sa.Column('address_line', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=False),
    sa.Column('neighborhood', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('pricing_mode', sa.Enum('PER_HOUR', 'PER_DAY', 'FIXED', name='listingpricingmode'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_per_hour', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('weekday_discount_percent', sa.Integer(), nullable=True),
    sa.Column('delivery_available', sa.Boolean(), nullable=True),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('delivery_radius_km', sa.Integer(), nullable=True),
    sa.Column('delivery_description', sa.Text(), nullable=True),
    sa.Column('space_type', sa.String(), nullable=True),
    sa.Column('size_length', sa.Float(), nullable=True),
    sa.Column('size_width', sa.Float(), nullable=True),
    sa.Column('depth_min', sa.Float(), nullable=True),
    sa.Column('depth_max', sa.Float(), nullable=True),
    sa.Column('is_outdoor', sa.Boolean(), nullable=True),
    sa.Column('is_ada_friendly', sa.Boolean(), nullable=True),
    sa.Column('accessibility_description', sa.Text(), nullable=True),
    sa.Column('num_courts', sa.Integer(), nullable=True),
    sa.Column('court_type', sa.String(), nullable=True),
    sa.Column('area_sqft', sa.Integer(), nullable=True),
    sa.Column('allows_parties', sa.Boolean(), nullable=True),
    sa.Column('allows_smoking', sa.Boolean(), nullable=True),
    sa.Column('allows_alcohol', sa.Boolean(), nullable=True),
    sa.Column('allows_loud_music', sa.Boolean(), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('min_hours', sa.Integer(), nullable=True),
    sa.Column('max_hours', sa.Integer(), nullable=True),
    sa.Column('max_guests', sa.Integer(), nullable=False),
    sa.Column('allows_pets', sa.Boolean(), nullable=True),
    sa.Column('pet_rules', sa.Text(), nullable=True),
    sa.Column('allows_children', sa.Boolean(), nullable=True),
    sa.Column('allows_infants', sa.Boolean(), nullable=True),
    sa.Column('check_in_type', sa.String(), nullable=True),
    sa.Column('has_restroom', sa.Boolean(), nullable=True),
    sa.Column('restroom_description', sa.String(), nullable=True),
    sa.Column('has_parking', sa.Boolean(), nullable=True),
    sa.Column('parking_description', sa.String(), nullable=True),
    sa.Column('parking_capacity', sa.Integer(), nullable=True),
    sa.Column('has_street_parking', sa.Boolean(), nullable=True),
    sa.Column('has_paid_parking', sa.Boolean(), nullable=True),
    sa.Column('has_parking_lot', sa.Boolean(), nullable=True),
    sa.Column('privacy_level', sa.String(), nullable=True),
    sa.Column('privacy_description', sa.Text(), nullable=True),
    sa.Column('tour_360_url', sa.String(), nullable=True),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('badges', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cancellation_policy', sa.Enum('FLEXIVEL', 'MODERADA', 'RIGOROSA', name='cancellationpolicy'), nullable=True),
    sa.Column('cancellation_hours_before', sa.Integer(), nullable=True),
    sa.Column('security_deposit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_highly_rebooked', sa.Boolean(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('total_bookings', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('availability_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('price_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('total_hours', sa.Integer(), nullable=False),
    sa.Column('num_guests', sa.Integer(), nullable=False),
    sa.Column('num_adults', sa.Integer(), nullable=True),
    sa.Column('num_children', sa.Integer(), nullable=True),
    sa.Column('num_infants', sa.Integer(), nullable=True),
    sa.Column('num_pets', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('addons_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('service_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('host_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('host_payout', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_address', sa.String(), nullable=True),
    sa.Column('deposit_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deposit_status', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED_BY_GUEST', 'CANCELLED_BY_HOST', 'COMPLETED', 'DISPUTED', name='bookingstatus'), nullable=True),
    sa.Column('guest_message', sa.Text(), nullable=True),
    sa.Column('host_response', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'space_id', name='uq_user_space_favorite')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reported_user_id', sa.UUID(), nullable=True),
    sa.Column('reported_space_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Enum('FAKE_LISTING', 'HARASSMENT', 'DAMAGE', 'FRAUD', 'INAPPROPRIATE', 'OTHER', name='reportreason'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'RESOLVED', 'DISMISSED', name='reportstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reported_space_id'], ['spaces.id'], ),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('space_addons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pricing_type', sa.Enum('FLAT', 'PER_HOUR', 'PER_UNIT', name='addonpricingtype'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('space_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('is_cover', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('space_pricing_tiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=False),
    sa.Column('min_guests', sa.Integer(), nullable=False),
    sa.Column('max_guests', sa.Integer(), nullable=False),
    sa.Column('price_per_hour', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('space_promotions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('PERCENTAGE', 'FIXED_AMOUNT', name='promotiontype'), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('min_hours', sa.Integer(), nullable=True),
    sa.Column('min_guests', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_addons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('addon_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['addon_id'], ['space_addons.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('space_id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('payer_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('host_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'REFUNDED', 'FAILED', name='paymentstatus'), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('stripe_transfer_id', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('reviewee_id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('GUEST_TO_HOST', 'HOST_TO_GUEST', name='reviewtype'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('cleanliness_rating', sa.Integer(), nullable=True),
    sa.Column('accuracy_rating', sa.Integer(), nullable=True),
    sa.Column('communication_rating', sa.Integer(), nullable=True),
    sa.Column('value_rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['reviewee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('reviews')
    op.drop_table('payments')
    op.drop_table('conversations')
    op.drop_table('booking_addons')
    op.drop_table('space_promotions')
    op.drop_table('space_pricing_tiers')
    op.drop_table('space_images')
    op.drop_table('space_addons')
    op.drop_table('reports')
    op.drop_table('favorites')
    op.drop_table('bookings')
    op.drop_table('availability_rules')
    op.drop_table('spaces')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
