"""fase3_fase4_models

Revision ID: c2be76bac7b9
Revises: 4a7da3c07e64
Create Date: 2026-07-14 11:42:53.856673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2be76bac7b9'
down_revision: Union[str, None] = '4a7da3c07e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklists_type'), 'blacklists', ['type'], unique=False)
    op.create_index(op.f('ix_blacklists_value'), 'blacklists', ['value'], unique=False)
    op.create_table('device_fingerprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('device_model', sa.String(), nullable=True),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('app_version', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_fingerprints_device_id'), 'device_fingerprints', ['device_id'], unique=False)
    op.create_table('terms_acceptances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('availability_exceptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_exceptions_date'), 'availability_exceptions', ['date'], unique=False)
    op.create_table('blocked_dates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocked_dates_date'), 'blocked_dates', ['date'], unique=False)
    op.create_table('custom_pricing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('price_per_hour', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_pricing_date'), 'custom_pricing', ['date'], unique=False)
    op.add_column('spaces', sa.Column('price_per_hour_weekend', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('spaces', sa.Column('price_per_hour_holiday', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('spaces', sa.Column('buffer_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spaces', 'buffer_minutes')
    op.drop_column('spaces', 'price_per_hour_holiday')
    op.drop_column('spaces', 'price_per_hour_weekend')
    op.drop_index(op.f('ix_custom_pricing_date'), table_name='custom_pricing')
    op.drop_table('custom_pricing')
    op.drop_index(op.f('ix_blocked_dates_date'), table_name='blocked_dates')
    op.drop_table('blocked_dates')
    op.drop_index(op.f('ix_availability_exceptions_date'), table_name='availability_exceptions')
    op.drop_table('availability_exceptions')
    op.drop_table('terms_acceptances')
    op.drop_index(op.f('ix_device_fingerprints_device_id'), table_name='device_fingerprints')
    op.drop_table('device_fingerprints')
    op.drop_index(op.f('ix_blacklists_value'), table_name='blacklists')
    op.drop_index(op.f('ix_blacklists_type'), table_name='blacklists')
    op.drop_table('blacklists')
    # ### end Alembic commands ###
